import React, { useEffect } from "react";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import { useRouter } from "next/router";
import {
  Flex,
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
  Text,
  Button,
} from "@chakra-ui/react";

const StatusPage = ({ status }) => {
  const router = useRouter();
  const handleRedirect = () => {
    router.push("/");
  };

  return (
    <div>
      <Head>
        <title>Uber Eats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Flex justify="center" align="center" mt="100px" height="500px">
        <Alert
          status={status === "success" ? status : "warning"}
          variant="subtle"
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          height="500px"
        >
          <AlertIcon boxSize="40px" mr={0} />
          <AlertTitle mt={4} mb={1} fontSize="lg">
            {status === "success" ? "Success!" : "Oops..."}
          </AlertTitle>
          <AlertDescription maxWidth="sm">
            <Flex
              flexDir="column"
              mt="20px"
              rowGap="20px"
              justify="center"
              align="center"
            >
              <Text>
                {status === "success"
                  ? "Thanks for your order!"
                  : status === "warning"
                  ? "Looks like you have cancelled your payment."
                  : "Something went wrong..."}
              </Text>

              {status === "success" ? <Text>We will work on it!</Text> : <></>}
              <Button
                width="150px"
                colorScheme="green"
                onClick={handleRedirect}
              >
                Back To Home
              </Button>
            </Flex>
          </AlertDescription>
        </Alert>
      </Flex>
    </div>
  );
};

export default StatusPage;

export const getServerSideProps = async ({ params }) => {
  return {
    props: params,
  };
};
