import React from "react";
import Head from "next/head";
import Navbar from "../../components/Navbar";
import Signin from "../../components/auth/Signin";

const signin = () => {
  return (
    <div>
      <Head>
        <title>Uber Eats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Signin />
    </div>
  );
};

export default signin;
