import React from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { useRouter } from "next/router";
import {
  Flex,
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
  Text,
  Button,
} from "@chakra-ui/react";

const Success = () => {
  const router = useRouter();
  const handleRedirect = () => {
    router.push("/");
  };
  return (
    <div>
      <Head>
        <title>Uber Eats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Flex justify="center" align="center" mt="100px" height="500px">
        <Alert
          status="success"
          variant="subtle"
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          height="500px"
        >
          <AlertIcon boxSize="40px" mr={0} />
          <AlertTitle mt={4} mb={1} fontSize="lg">
            Success!
          </AlertTitle>
          <AlertDescription maxWidth="sm">
            <Flex flexDir="column" mt="20px" rowGap="20px">
              <Text>Thanks for your order!</Text>
              <Text>We will work on it!</Text>
              <Button colorScheme="green" onClick={handleRedirect}>
                Back To Home
              </Button>
            </Flex>
          </AlertDescription>
        </Alert>
      </Flex>
    </div>
  );
};

export default Success;
